[build]
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NETLIFY_DB_URL = "postgresql://netlifydb_owner:npg_Qj0bIAg5RxMC@ep-aged-forest-ajlyudoc.c-3.us-east-2.db.netlify.com/netlifydb?sslmode=require"

[[redirects]]
  from = "/api/tracking"
  to = "/.netlify/functions/tracking"
  status = 200

[[redirects]]
  from = "/api/admin"
  to = "/.netlify/functions/admin"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
